import type { Metadata } from "next";
import "./globals.css";
import { AppProviders } from "@/components/providers";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en" data-scroll-behavior="smooth" suppressHydrationWarning>
      <body className="antialiased" suppressHydrationWarning>
    <AppProviders >
        {children}
    </AppProviders>
      </body>
    </html>
  );
}
